apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    backstage.io/kubernetes-id: test-app
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
  namespace: test
spec:
  components:
    - name: test-app
      type: webservice
      properties:
        image: docker.io/shashankram/sample-react-app:latest
        ports:
          - port: 80
            expose: true
        labels:
          app: test-app
      traits:
        - type: scaler
          properties:
            replicas: 1
        - type: argocd
          properties:
            name: argocd
---
